# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5096b1a179f2f51e70aba2f000a5d14fe882ac278e8771c3d1c17eb374833fac5c071030eeab44721dc68347ab88686a35f03efebd5b0b8b4e0fa295143f3d

test:
  secret_key_base: b33c825dc8a2c75d09fddb108f5e03a7488087cf741e9461aa887ebe1b67b2fbb57fc89f871ebe7aed67499bbd5ce4e50c8a39832447ddbf863debc31bc0caff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
